### PR TITLE
Luish dev branch

### PR DESCRIPTION
**Pull request by hernandezluise**
made changes in pricing from $7500 to $8000 since thats the pricing that shows on the pricing tab.

### CODE REVIEW

**Review by cgbridgewater — APPROVED** [review]
I'm still torn on how to word the pricing, as 7500 is the starting point, with an upfront payment.  

I'll push this through to get them matching but I think it'll eventually change to "$7500*"   somewhere will have the  "(*with upfront payment credit applied)"

That way we can advertise a lower starting point.

**Comment by hernandezluise** [comment]
I think once they checkout, we can give them a "discount" if they are paying upfront. I feel like that would be a great way to word it.

**Comment by cgbridgewater** [comment]
Agreed.  It would be good to find a way to be able to advertise "classes starting at xxx", to give a lower price point. 

But don't want to give a "bait and switch" feel either.

**Comment by hernandezluise** [comment]
Payment options we offer, "full financing available " , or receive "xxx discount" for paying in full. 
That way people who get financing don't feel like we are advertising as 2 different prices and it's consistent $xxx cost across the website.

**Pull request merged**
